table users {
  id serial [pk]
  created_at TIMESTAMP
  updated_at TIMESTAMP
  username varchar(30) [unique]
  bio varchar(400)
  avatar varchar(200)
  phone varchar(15) [unique]
  email varchar(100) 
  password varchar(100) 
  status_id INTEGER [ref: - status.id] 
}

table status {
  id serial [pk]
  title varchar(50)
}

table posts {
  id serial [pk]
  created_at TIMESTAMP
  updated_at TIMESTAMP
  content varchar
  user_id INTEGER [ref: > users.id]
  url varchar(200)
  latitude REAL
  longitude REAL
}

table tagged_user {
  id serial [pk]
  created_at TIMESTAMP
  updated_at TIMESTAMP
  post_id INTEGER [ref: > posts.id]
  user_id INTEGER [ref: > users.id]
}

table comments {
  id serial [pk]
  created_at TIMESTAMP
  updated_at TIMESTAMP
  title varchar
  user_id INTEGER [ref: > users.id]
  post_id INTEGER [ref: > posts.id]
}

table hashtag {
  id serial [pk]
  title varchar
  created_at TIMESTAMP

}

table post_likes {
  id serial [pk]
  created_at TIMESTAMP
  updated_at TIMESTAMP
  user_name INTEGER [ref: - users.id]
}

table comment_likes {
  id serial [pk]
  created_at TIMESTAMP
  updated_at TIMESTAMP
  post_id INTEGER [ref: - posts.id]
}

table post_hashtag {
  id serial [pk]
  hashtag_id INTEGER [ref: > hashtag.id]
  post_id INTEGER [ref: < posts.id]
}

table comment_hashtag {
  id serial [pk]
  hashtag_id INTEGER [ref: > hashtag.id]
  comment_id INTEGER [ref: < comments.id]
}

table bio_hashtag {
  id serial [pk]
  hashtag_id INTEGER [ref: > hashtag.id]
  user_id INTEGER [ref: < users.id]
}

table follower {
  id serial [pk]
  created_at TIMESTAMP
  updated_at TIMESTAMP
  leader_id INTEGER [ref: > users.id]
  follower_id INTEGER [ref: > users.id]
}